language: go

go:
  - 1.3
  - master

install:
  - make get-deps

script:
  - make test

notifications:
  slack:
    secure: lGA44Lx1rJjBrth9sYVmwIwQPChP5JDKK+oYFnOol9Hmlc/VR/++oq66teGNuTdIlD0EZdUJl8T3rw4nkjt7ARR3tEVDZGkpYYa6yAjPpTnmBWNOIrFjInDHbcTGv+jci30lFEvOeSMMoU3A++rg6mObJvMhQZIpTBZEgXzNJNvqdrvQ5Gm1rHaLhFrgoD9PKH9N6wXi9HQDyky0Bw+98uNM3x8vNYz4XvqbFB26UD1502VzsKSaPrzMoAKlDZ4bQwMdWKRX6sCRXVnDZxkWi0s9fjFCUhoro4gcI7sBUOOaRxV5o0DaaI2rTKJ1wpphV1wSYWiuuJSBVdsd0j6teF+ScrOKYtHAEqcBGbdOhQEhG9ucFUTxyd9c5N1WWWTRHwvvuDb7inIOua6KgG4Sz0SbwLs8TrPZiaSR2+ckGhlK87EPBpqYZWhdPBA/m8xEFdb1hw1jj6VttvQvHPfL1pSvnzZyBxQiRX58nMOJvDHsgVQn4atsgFsxCMLw8yBnap0/sUlC6/CywJuvxNdc8g7Ew18MdpyTKrHcqYDBR7RVaSHCxj1lETLRNJtW9BbrbMMrJI7rcWK4iyZuzB26FEiwfX6MiAdAXu7SsUIgrAfXLwsWlnSuQXl/e0cXRNzylPkiGEDAojRkhMaupnKR4USkg5oxAzxylPdnVn4youo=
